#!/bin/sh
#
# @name Ninano Bubo 4s
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Geunchan Kim <geunchan@ninanobiz.com>
#

. ${R}etc/init.d/rc.mc_defaults

# -------------------------------------------------------
# Control Allocation (CA) - Airframe & Rotor Setup
# -------------------------------------------------------

# Attitude Rate PID tuning (reduced gains to prevent high-frequency oscillations due to low inertia)
param set-default MC_ROLL_P 4
param set-default MC_ROLLRATE_K 0.7
param set-default MC_ROLLRATE_P 0.101
param set-default MC_ROLLRATE_I 0.138
param set-default MC_ROLLRATE_D 0.0036

param set-default MC_PITCH_P 4
param set-default MC_PITCHRATE_K 0.7
param set-default MC_PITCHRATE_P 0.099
param set-default MC_PITCHRATE_I 0.137
param set-default MC_PITCHRATE_D 0.0036

param set-default MC_YAW_P 4
param set-default MC_YAWRATE_P 0.116
param set-default MC_YAWRATE_I 0.124
param set-default MC_YAWRATE_D 0.0045

# Altitude control damping
param set-default MPC_Z_VEL_P_ACC 1.6
param set-default MPC_Z_VEL_I_ACC 1.0
param set-default MPC_Z_P 0.3

# Flight Mode Parameter
param set-default RC_MAP_FLTMODE 5
param set-default COM_FLTMODE1 0
param set-default COM_FLTMODE2 0
param set-default COM_FLTMODE3 1
param set-default COM_FLTMODE4 1
param set-default COM_FLTMODE5 2
param set-default COM_FLTMODE6 2

# Horizontal cruise speed when auto mode
param set-default MPC_XY_CRUISE 10

# CA_AIRFRAME: Airframe type (0 = Multirotor)
param set-default CA_AIRFRAME 0

# CA_ROTOR_COUNT: Total rotor count
param set-default CA_ROTOR_COUNT 4

# --- Rotor 0: Front-Right ---
param set-default CA_ROTOR0_PX 0.230
param set-default CA_ROTOR0_PY 0.2275
param set-default CA_ROTOR0_KM 0.05 # + = CCW

# --- Rotor 1: Rear-Left ---
param set-default CA_ROTOR1_PX -0.230
param set-default CA_ROTOR1_PY -0.2275
param set-default CA_ROTOR1_KM 0.05 # + = CCW

# --- Rotor 2: Front-Left ---
param set-default CA_ROTOR2_PX 0.230
param set-default CA_ROTOR2_PY -0.2275
param set-default CA_ROTOR2_KM -0.05 # - = CW

# --- Rotor 3: Rear-Right ---
param set-default CA_ROTOR3_PX -0.230
param set-default CA_ROTOR3_PY 0.2275
param set-default CA_ROTOR3_KM -0.05 # - = CW

# -------------------------------------------------------
# PWM Output Channel - Motor Function Mapping
# -------------------------------------------------------

# PWM_MAIN_FUNC1~4: Motor function mapping (101-104 = Motors 1-4)
param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
